CinnabarLabStorageRoom_Script:
	call EnableAutoTextBoxDrawing
	ret

CinnabarLabstorageRoom_TextPointers:
	dw CinnabarLabstorageRoomtext1

CinnabarLabstorageRoomtext1:
	text_far _CinnabarLabstorageRoomtext1
	text_end
